### ISSUE TITLE
NodeJS SDK: Promises created as per `pollingInterval` can reject and crash the process

### ISSUE THREAD

**Issue by matthewdavidson** [DevCycleHQ/js-sdks#308]
See [line 44 of environmentConfigManager.ts](https://github.com/DevCycleHQ/js-sdks/blob/main/sdk/nodejs/src/environmentConfigManager.ts#L44) - whilst the initial `fetchConfigPromise` is exposed to consumers so that they can handle any rejections accordingly, the subsequent fetch promises that are created per line 44 according to the polling interval are not exposed to consumer land and therefore if any of them fail, they can result in an unhandled rejections ([line 82](https://github.com/DevCycleHQ/js-sdks/blob/main/sdk/nodejs/src/environmentConfigManager.ts#L82)). This could potentially stop our node server process from being able to start (during autoscaling for instance) if there was an issue downloading dev cycle config.

Note: this would only happen if both the initial dev cycle config failed as well as subsequent polls. In other words, if the initial dev cycle config download success, consumers wont run into this issue.

**Comment by jonathannorris** [comment]
Hey @matthewdavidson thanks for letting us know about this issue. You are correct that the intention of this code is to only throw if the initial config fails to be fetched (generally because of invalid SDK keys). So we should adjust the `setInterval()` to only be started once the original config has loaded. Will let you know once that change has been pushed.

However, this could cause a situation where the calling application catches the initially thrown exception and a successful config is never fetched. We do retry the config requests multiple times from our CDN, so that should be a very rare circumstance, however we will need to think through that edge-case.

**Comment by jonathannorris** [comment]
@matthewdavidson `1.4.14` has been published with the fix linked above.
