### ISSUE TITLE
Realtime updates don't work if devcycle is initialized with isAnonymous and later on identifies a user.

### ISSUE THREAD

**Issue by phi-tz** [DevCycleHQ/js-sdks#338]
Looking at the code [here](https://github.com/DevCycleHQ/js-sdks/blob/main/sdk/js/src/Client.ts#L88), it looks like we are only starting a `StreamingConnection` on initialization.  No connection is created on calling `identifyUser`.  Is that indented?

**Comment by elliotCamblor** [comment]
Just for clarification, are you experiencing issues with the streaming connection opening on initialization?

The expected behaviour with realtime updates is that the streaming connection should open on initialization regardless of if the user is anonymous or not. Because of this there is no need to re-open the connection on `identifyUser`

**Comment by phi-tz** [comment]
Ah you are right.  After a few debugging session, I confirm that the streaming connection is indeed created on initialization.

I think the issue comes from the fact that this is react native, which doesnt have `document` and its visibility.

**Comment by phi-tz** [comment]
Also for posterity, on React Native, establishing a streaming connection throws this error: `[ReferenceError: Can't find variable: EventSource]`

**Comment by nikolasleblanc** [comment]
Hey @phi-tz thanks for your input! If you send me your email address I'd love to send you some thank you swag! Email me at nik@devcycle.com.
