### ISSUE TITLE
useIsDevCycleInitialized never returns true

### ISSUE THREAD

**Issue by mikkoh** [DevCycleHQ/js-sdks#667]
I upgraded from: `@devcycle/react-client-sdk@1.11.11` -> `@devcycle/react-client-sdk@1.14.3`

After this upgrade `useIsDevCycleInitialized` never returns `true`

To identify the breaking version I installed all releases between `1.11.11` and `1.14.3`

It seems like the breaking change was introduced at `@devcycle/react-client-sdk@1.13.1`

If I install `@devcycle/react-client-sdk@1.13.0` everything is fine.

**Comment by ajwootto** [comment]
@mikkoh thanks for the report, we'll take a look right away

**Comment by ajwootto** [comment]
@mikkoh a few questions about your setup:

Are you using the "deferredInitialization" option?

Is this issue happening in a development build or production (or both)? If development, are you using React Strict Mode?

If available it would also help if you could provide a reproducible example. In the meantime I'll continue digging.

**Comment by mikkoh** [comment]
Yes. I'm using `deferredInitialization`. Both in dev and prod. Discovered in prod had to revert immediately. 😬 Was able to repro in dev. 

```jsx
const AppWithDevcycle = withDevCycleProvider({
  sdkKey: DEV_CYCLE_KEY,
  options: {
    deferInitialization: true,
  },
})(App);
```

Yes using `StrictMode`.

I don't have a URL where you could test.

**Comment by ajwootto** [comment]
To provide more info about what might be going on here, in several versions before `1.13.1` the `deferInitialization` option was erroneously being ignored by the SDK, and was treated as always having a value of "false" even when enabled. That was fixed in that version, which would lead to a scenario in your case where the option that was previously doing nothing is now correctly enabling deferred initialization. 

In deferred mode the SDK won't start initialization until `identifyUser` is called with some user data, and until that happens the `useIsDevCycleInitialized` method will return false. More info about that [here](https://docs.devcycle.com/sdk/client-side-sdks/react/react-gettingstarted#deferred-initialization)

If identifyUser is indeed being called, then we definitely still have an issue here. Let me know if that's the case!

**Comment by ajwootto** [comment]
Hi @mikkoh, just following up to see if you've had a chance to review the above info.

**Comment by ajwootto** [comment]
@mikkoh we just released another fix for the SDK to resolve some issues with the client being "cleaned up" on unmount which caused issues in React Strict mode with the "double" execution of `useEffect` (and thus was likely causing problems anywhere else that React decided to re-execute the effect). That may have also led to the behaviour you were experiencing here so I'd encourage trying out the latest version of the SDK.

**Comment by mikkoh** [comment]
I ended up removing the library temporarily. If I end up adding it back again I can double check if things are ok.

**Comment by ajwootto** [comment]
@mikkoh going to resolve this issue for now as I believe any issues that may have caused this are addressed. Let me know if you get a chance to try again and feel free to re-open if you're still experiencing problems
